[project]
name = "kezura"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "clerk-backend-api>=4.1.3",
    "cloudinary>=1.44.1",
    "flask>=3.1.2",
    "flask-sqlalchemy>=3.1.1",
    "quas-docs>=0.0.2",
]
